apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgd
  namespace: bgd
  labels:
    app: bgd
spec:
  replicas: 3   # 1에서 3으로 수정
  selector:
    matchLabels:
      app: bgd

  template:
    metadata:
      labels:
        app: bgd    # 서비스의 label과 일치, matchLabels와 일치
      creationTimestamp: null
    spec:
      containers:
      - name: bgd
        image: quay.io/rhdevelopers/bgd:1.0.0
        env:
        - name: COLOR
          value: "red"  # blue -> red