apiVersion: v1
kind: Service
metadata:
  name: hello-app-svc
  namespace: hello-app
spec:
  # pod와 클라이언트를 연결하기 위해 서비스가 NodePort 또는 노드발란서를 이용해 url로 외부와 연결
  type: NodePort
  selector:
    # deployment의 label과 일치(연결고리)
    app: hello-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
