apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kustomization이 관리할 리소스 목록을 정의
resources:
- hello-app-namespace.yaml
- hello-app-deployment.yaml
- hello-app-service.yaml
# 본인의 도커 허브 사용자 이름으로 변경
images:
- name: yeonju94/hello-app
  newName: yeonju94/hello-app
  newTag: 0f1234d
